workspace "Demo"
  configurations { "Debug", "Release" }
project"Demo"
  kind "ConsoleApp"
  language "C"
filter "configurations:Debug"
  sysincludedirs  {"$(VC_IncludePath)"}
  defines { "_IAR_", "__ICCARM__", "_Pragma(x)=", "__interrupt=" }
  forceincludes { "" }
  includedirs { "", "STM8L15x_StdPeriph_Driver/inc", "Hardware" }
  files { "Hardware/apply.c", "Hardware/comconfig.c", "Hardware/Crc8.c", "Hardware/DriverConfig.c", "Hardware/DriverConfig.h", "Hardware/ds18b20.c", "Hardware/flash.c", "Hardware/gy3x.c", "Hardware/iwdg.c", "Hardware/led.c", "Hardware/sht2x.c", "Hardware/sx1278.c", "Hardware/tim2.c", "Hardware/usart_t.c", "Hardware/usart_t.h", "STM8L15x_StdPeriph_Driver/src/stm8l15x_adc.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_clk.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_dac.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_exti.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_flash.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_gpio.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_itc.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_iwdg.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_pwr.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_rtc.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_spi.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_syscfg.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_tim2.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_tim4.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_usart.c", "main.c", "STM8L15x_StdPeriph_Driver/inc/stm8l15x.h", "stm8l15x_conf.h", "stm8l15x_it.c", "stm8l15x_it.h" }
  vpaths {["Hardware"] = { "Hardware/apply.c" , "Hardware/comconfig.c" , "Hardware/Crc8.c" , "Hardware/DriverConfig.c" , "Hardware/DriverConfig.h" , "Hardware/ds18b20.c" , "Hardware/flash.c" , "Hardware/gy3x.c" , "Hardware/iwdg.c" , "Hardware/led.c" , "Hardware/sht2x.c" , "Hardware/sx1278.c" , "Hardware/tim2.c" , "Hardware/usart_t.c" , "Hardware/usart_t.h" } , ["STM8L15x_StdPeriph_Driver"] = { "STM8L15x_StdPeriph_Driver/src/stm8l15x_adc.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_clk.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_dac.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_exti.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_flash.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_gpio.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_itc.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_iwdg.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_pwr.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_rtc.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_spi.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_syscfg.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_tim2.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_tim4.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_usart.c" } , ["User"] = { "main.c" , "STM8L15x_StdPeriph_Driver/inc/stm8l15x.h" , "stm8l15x_conf.h" , "stm8l15x_it.c" , "stm8l15x_it.h" } }
filter "configurations:Release"
  sysincludedirs  {"$(VC_IncludePath)"}
  defines { "NDEBUG", "_IAR_", "__ICCARM__", "_Pragma(x)=", "__interrupt=" }
  forceincludes { "" }
  includedirs { "" }
  files { "Hardware/apply.c", "Hardware/comconfig.c", "Hardware/Crc8.c", "Hardware/DriverConfig.c", "Hardware/DriverConfig.h", "Hardware/ds18b20.c", "Hardware/flash.c", "Hardware/gy3x.c", "Hardware/iwdg.c", "Hardware/led.c", "Hardware/mq137.c", "Hardware/sht2x.c", "Hardware/sx1278.c", "Hardware/tim2.c", "Hardware/usart_t.c", "Hardware/usart_t.h", "STM8L15x_StdPeriph_Driver/src/stm8l15x_adc.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_clk.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_dac.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_exti.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_flash.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_gpio.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_itc.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_iwdg.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_pwr.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_rtc.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_spi.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_syscfg.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_tim2.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_tim4.c", "STM8L15x_StdPeriph_Driver/src/stm8l15x_usart.c", "main.c", "STM8L15x_StdPeriph_Driver/inc/stm8l15x.h", "stm8l15x_conf.h", "stm8l15x_it.c", "stm8l15x_it.h" }
  vpaths {["Hardware"] = { "Hardware/apply.c" , "Hardware/comconfig.c" , "Hardware/Crc8.c" , "Hardware/DriverConfig.c" , "Hardware/DriverConfig.h" , "Hardware/ds18b20.c" , "Hardware/flash.c" , "Hardware/gy3x.c" , "Hardware/iwdg.c" , "Hardware/led.c" , "Hardware/mq137.c" , "Hardware/sht2x.c" , "Hardware/sx1278.c" , "Hardware/tim2.c" , "Hardware/usart_t.c" , "Hardware/usart_t.h" } , ["STM8L15x_StdPeriph_Driver"] = { "STM8L15x_StdPeriph_Driver/src/stm8l15x_adc.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_clk.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_dac.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_exti.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_flash.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_gpio.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_itc.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_iwdg.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_pwr.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_rtc.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_spi.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_syscfg.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_tim2.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_tim4.c" , "STM8L15x_StdPeriph_Driver/src/stm8l15x_usart.c" } , ["User"] = { "main.c" , "STM8L15x_StdPeriph_Driver/inc/stm8l15x.h" , "stm8l15x_conf.h" , "stm8l15x_it.c" , "stm8l15x_it.h" } }
premake.override(premake.vstudio.vc2010, "includePath", function(base,cfg)
   local dirs = premake.vstudio.path(cfg, cfg.sysincludedirs)
    if #dirs > 0 then
    premake.vstudio.vc2010.element("IncludePath", nil, "%s", table.concat(dirs, ";"))
    end
end)